<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DynamicSpriteFontSample.Core\DynamicSpriteFontSample.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\external\MonoGame\Artifacts\native\mgruntime\desktopvk\windows\x64\Release\mgruntime.dll"
             Condition="Exists('..\..\external\MonoGame\Artifacts\native\mgruntime\desktopvk\windows\x64\Release\mgruntime.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\external\MonoGame\Artifacts\native\mgruntime\desktopvk\linux\x64\Release\libmgruntime.so"
             Condition="Exists('..\..\external\MonoGame\Artifacts\native\mgruntime\desktopvk\linux\x64\Release\libmgruntime.so')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\external\MonoGame\Artifacts\native\mgruntime\desktopvk\macos\Release\libmgruntime.dylib"
             Condition="Exists('..\..\external\MonoGame\Artifacts\native\mgruntime\desktopvk\macos\Release\libmgruntime.dylib')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
