<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DynamicSpriteFontSample.Core\DynamicSpriteFontSample.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\external\MonoGame\Artifacts\native\mgruntime\windowsdx\windows\x64\Release\mgruntime.dll"
             Condition="Exists('..\..\external\MonoGame\Artifacts\native\mgruntime\windowsdx\windows\x64\Release\mgruntime.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
